# Generated by Django 3.1.4 on 2020-12-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=256)),
                ('harga', models.BigIntegerField()),
                ('part_nomor_barang', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id_detail_penjualan', models.IntegerField(primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.barang')),
            ],
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merek', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('harga_total', models.BigIntegerField()),
                ('barangs', models.ManyToManyField(through='datacenter.DetailPenjualan', to='datacenter.Barang')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.pembeli')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_order', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('barang_datang', models.BooleanField()),
                ('tanggal_datang', models.DateTimeField(blank=True, default='', null=True)),
                ('batal', models.BooleanField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.barang')),
            ],
        ),
        migrations.AddField(
            model_name='detailpenjualan',
            name='penjualan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.penjualan'),
        ),
        migrations.AddField(
            model_name='barang',
            name='merek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.merek'),
        ),
    ]
