# Generated by Django 3.1.4 on 2021-01-07 14:04

from django.db import migrations, models
import webclient.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_barang_harga_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='barang',
        ),
        migrations.AddField(
            model_name='order',
            name='nama_barang',
            field=webclient.fields.NameField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga_preview',
            field=models.CharField(default='Rp. -', max_length=16),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama_barang',
            field=webclient.fields.NameField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='pembeli',
            name='nama_pembeli',
            field=webclient.fields.NameField(max_length=256),
        ),
    ]
