# Generated by Django 3.1.4 on 2021-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_auto_20210107_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='harga',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='jumlah',
            field=models.IntegerField(default=1),
        ),
    ]
