# Generated by Django 3.1.4 on 2021-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_auto_20210109_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
