# Generated by Django 3.1.4 on 2021-01-09 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_auto_20210109_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
