# Generated by Django 3.1.4 on 2021-01-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_auto_20210109_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpenjualan',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='detailpenjualan',
            name='total_harga',
        ),
    ]
