# Generated by Django 3.1.4 on 2021-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_auto_20210117_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='location',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AddField(
            model_name='barang',
            name='preview_image',
            field=models.ImageField(default=None, null=True, upload_to='items/'),
        ),
    ]
