# Generated by Django 3.1.4 on 2021-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0009_auto_20210122_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='unit_type',
            field=models.CharField(default='pcs', max_length=128),
        ),
        migrations.AlterField(
            model_name='barang',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
